### ISSUE TITLE
注文管理(BitMEX)で価格の小数部分が表示されない

### ISSUE THREAD

**Issue by mizuka123** [kurosuinc/CrossTraderIssues#14]
## 同様の内容がないか、既存の不具合報告一覧はご確認いただけましたか？
はい

## エディションとバージョン
PRO版 v1.0.35

## 不具合が発生する直前に行った行動
表示なので操作は行っていません

## 期待される動作
価格が小数まで表示される

## 実際に発生した動作
価格が整数しか表示されない

## 発生時のスクリーンショット
![2019-06-08_09h20_07](https://user-images.githubusercontent.com/5837315/59139544-9eae4480-89ce-11e9-8b32-22b5e2b2afbb.png)

## クラッシュ時のエラーログの内容
クラッシュではないのでありません

## お使いのPCの環境
![2019-06-08_09h21_46](https://user-images.githubusercontent.com/5837315/59139584-e59c3a00-89ce-11e9-9642-29af628f7b4f.png)

**Comment by supermomonga** [comment]
表示部分で小数点を丸めてしまっている様ですので、次のバージョンで修正させて頂きます。

**Comment by supermomonga** [comment]
v1.1.2 リリースにて修正が完了しました
