### ISSUE TITLE
bFのチャートで時間足の変更、チャートの移動などの操作が不可。

### ISSUE THREAD

**Issue by mizo7010** [kurosuinc/CrossTraderIssues#16]
## 同様の内容がないか、既存の不具合報告一覧はご確認いただけましたか？
（はい／いいえ でご回答ください。既存の不具合報告一覧は https://github.com/kurosuinc/CrossTraderIssues/labels/%E4%B8%8D%E5%85%B7%E5%90%88%E5%A0%B1%E5%91%8A こちらからご確認頂けます。）
はい
## エディションとバージョン
タイトルバーに表示されているエディションとバージョンをを記載してください（例：PRO版 v1.0.12β）
PRO v1.2.1
## 不具合が発生する直前に行った行動
（例：「チャート」ウィジェットを開こうとした）
（例：特に操作していないが、起動後時間が一定の時間が経過した際に発生した）
ソフトの立ち上げ、アップデート。
## 期待される動作
（例：「チャート」ウィジェットの追加に成功する）

## 実際に発生した動作
（例：アプリケーションがクラッシュしてしまった）
アップデート後bFチャートの移動や時間足の変更、足の大きさなどの操作が効かなくなった。
チャート右上に赤文字で互換表示と記されています。
<img width="582" alt="error" src="https://user-images.githubusercontent.com/47137726/71480810-6cffac80-283e-11ea-9554-75f3e9dc6547.PNG">

## 発生時のスクリーンショット
アプリケーションがクラッシュした場合は不要ですが、表示値や動作がおかしいなどといった場合には発生時のスクリーンショットを添えてください

## クラッシュ時のエラーログの内容
アプリケーションがクラッシュした（落ちてしまった）場合に原因の特定に必要となります。イベントビューアーによるエラーログの確認の手順（ https://crosstrader.app/manual/archives/65 ）で取得したエラーログの内容を添えてください。連続した3つの\`（バッククォート）で囲むときれいに表示されます。

```
例：ここにエラーログを貼り付けてください
```

## お使いのPCの環境
PC情報の確認方法（ https://crosstrader.app/manual/archives/85 ）を参考に撮影したスクリーンショットを添えてください

**Comment by supermomonga** [comment]
「LightChartウィジェット」につきまして、今までは内部的にChromiumというブラウザのエンジンを用いて表示しておりましたが、こちらに由来するトラブルが多かったため、最新のバージョンよりWindows OSネイティブのブラウザコンポーネントで表示する形となっております。

その際、一部の古いOSでは古いブラウザコンポーネントが搭載されていることにより、動作が不安定・一分機能が動作しない場合がございます。古いブラウザコンポーネントが利用されている際に「互換表示」と表示される形となっております。

Issueを登録して頂いた際のテンプレートにある「お使いのPCの環境」について未記入となっておりますので、詳細な状況を確認するため、お手数ですがこちらコメントにてご記載頂けますでしょうか。

**Comment by mizo7010** [comment]
失礼いたしました！
<img width="797" alt="キャプチャ" src="https://user-images.githubusercontent.com/47137726/71626119-ea586200-2c2e-11ea-92ca-466702e8a2f8.PNG">

**Comment by supermomonga** [comment]
一部の古いOSに搭載されている古いブラウザコンポーネントにて同様の現象が再現できました。
こちらはアプリケーション側の問題ではなくOS・コンポーネント側の問題であるため、レジストリの値を変更しブラウザコンポーネントの挙動を変更する必要がございます。

アップデートにてレジストリの値を変更する機能を搭載する予定ですが、取り急ぎ、下記の手順で手動にて対応が可能かと思われます。

-----

- レジストリ エディターを起動します
![image](https://user-images.githubusercontent.com/377137/71891132-39e7e200-3189-11ea-9d98-e0187cc2a7d2.png)

- `コンピューター\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_NINPUT_LEGACYMODE` に移動します
    - `FEATURE_NINPUT_LEGACYMODE` が存在しなければ、一旦`コンピューター\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl`に移動し右クリックから`FEATURE_NINPUT_LEGACYMODE`というキーを追加します
- 右クリックからDWORD値を追加します。![image](https://user-images.githubusercontent.com/377137/71890548-db6e3400-3187-11ea-9c48-40780abb0121.png)
- 「新しい値 #1」という名前が追加されるので、名前を「CrossTrader.exe」に変更します。
- 「CrossTrader.exe」をダブルクリックし、値を0に変更します
![image](https://user-images.githubusercontent.com/377137/71891480-1c674800-318a-11ea-91d9-a4c6102f7c84.png)


最終的に以下の様な形となります。

![image](https://user-images.githubusercontent.com/377137/71891312-b4186680-3189-11ea-9be7-6571d6dda3c4.png)


-----

また、CrossTraderの動作保証環境は最新アップデート適用のWindows 10 OSとなっておりますので、今後他の機能について古いOSでは動作しなくなる可能性もございます。

現時点で、Microsoftより古いOS（Windows7, Windows8.1）からWindows 10への無償アップグレードが提供されている様ですので、可能であればこちらのアップグレードを行うことを推奨致します（OSのアップグレード作業はあくまで自己責任のもと行っていただきます様お願い致します。）。
参考: https://vertys.net/windows7-8-8-1-free-upgrade-to-windows10/

**Comment by mizo7010** [comment]
windows10に無料アップデートすることにより上記の症状は改善されました。
ご報告が遅れまして申し訳ありませんでした。
ありがとうございました。

**Comment by supermomonga** [comment]
@mizo7010 ご確認ありがとうございます。Windows 10 にて解決されたとのこと、承知致しました。

古いOSでの挙動については後日マニュアルサイトに追記させて頂きます。
