### ISSUE TITLE
Bitfinexの板情報が更新されない

### ISSUE THREAD

**Issue by cono2** [kurosuinc/CrossTraderIssues#2]
## 同様の内容がないか、既存の不具合報告一覧はご確認いただけましたか？
はい

## エディションとバージョン
PRO版 v1.0.18β）

## 不具合が発生した際に行った行動
CrossTraderを再起動した

## 期待される動作
板情報が更新される

## 実際に発生した動作
最新価格に合わせた板が出るも板情報が更新されない

## 発生時のスクリーンショット
![image](https://user-images.githubusercontent.com/47059134/51788824-cf32d600-21c5-11e9-96d5-f3a4fb497beb.png)

## クラッシュ時のエラーログの内容
アプリケーションがクラッシュした（落ちてしまった）場合に原因の特定に必要となります。イベントビューアーによるエラーログの確認の手順（ https://crosstrader.app/manual/archives/65 ）で取得したエラーログの内容を添えてください。連続した3つの\`（バッククォート）で囲むときれいに表示されます。

```
例：ここにエラーログを貼り付けてください
```

## お使いのPCの環境
![image](https://user-images.githubusercontent.com/47059134/51788833-e40f6980-21c5-11e9-8669-9d1d9757ac4b.png)

**Comment by supermomonga** [comment]
`@みぞ#2249 ` さんからの追加情報

>GitHubにて既にcono2様に挙げて頂いております"Bitfinexの板情報が更新されない"に準ずるものなのですが、
>私の方でも数日前から統合板情報の一番手前の買い板に(恐らくその価格には)無いはずのfinex数百枚が常駐する現象が発生しております。

>3422$に500程あるようなのですが、CrossTraderの3422$には大きな板は見当たらないのでそれが常に一番手前の板に表示されてしまっている？ようにも見えますが、、、こちらの設定等による不具合でしたら申し訳ないですが、念のため参考に画像を添付しておきます。

![image](https://user-images.githubusercontent.com/377137/51896845-b2c6b180-23f0-11e9-9154-e2bf573d085a.png)

![image](https://user-images.githubusercontent.com/377137/51896852-b6f2cf00-23f0-11e9-94cf-3a406aa6cbf1.png)


![image](https://user-images.githubusercontent.com/377137/51896862-ba865600-23f0-11e9-845c-953b5b8f17cd.png)

**Comment by supermomonga** [comment]
v1.0.19βにて修正完了しました
