### ISSUE TITLE
決済注文で指定価格・指値にしたときに「ベース価格からの距離」を設定しても指定価格で発注される

### ISSUE THREAD

**Issue by mizuka123** [kurosuinc/CrossTraderIssues#7]
## 同様の内容がないか、既存の不具合報告一覧はご確認いただけましたか？
はい

## エディションとバージョン
PRO版 v1.0.29β

## 不具合が発生する直前に行った行動
決済注文を行った

## 期待される動作
指定価格から「ベース価格からの距離」だけ離れた価格で注文される

## 実際に発生した動作
指定価格のまま発注された

## 発生時のスクリーンショット
[![Image from Gyazo](https://i.gyazo.com/9d924a073c3c4a8232f63e7c31f6e13f.png)](https://gyazo.com/9d924a073c3c4a8232f63e7c31f6e13f)

## クラッシュ時のエラーログの内容
クラッシュではないのでありません

## お使いのPCの環境
[![Image from Gyazo](https://i.gyazo.com/5b2cc618efb531216f349d91297f7c9b.png)](https://gyazo.com/5b2cc618efb531216f349d91297f7c9b)

**Comment by supermomonga** [comment]
- [x] 修正完了（リリース待ち）

**Comment by supermomonga** [comment]
v1.0.30β リリースにて修正されました
